env:
  browser: false
  es6: true
extends:
  - '@devprice/eslint-config'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
ignorePatterns:
  - "*.js"
  - "**/build/**"
  - "karambit-generated/**"
