name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm --prefix integration ci
    - id: build-cache
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ github.sha }}
    - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
      run: npm run release

  upload-artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm ci --only=dev
    - id: build-cache
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ github.sha }}
    - if: ${{ steps.build-cache.outputs.cache-hit != 'true' }}
      name: Require cache
      run: exit 1
    - run: npm pack
    - uses: actions/upload-artifact@v3
      with:
        path: karambit-inject-*.tgz
        if-no-files-found: error
